# Contexte
Une entreprise possède plusieurs bâtiments équipés de capteurs IoT.
Chaque capteur collecte régulièrement des informations sur la température, l'humidité, la pression,
la consommation énergétique, l'état du capteur, le bâtiment, la date et l'heure de la mesure.
Les données doivent être préparées et analysées avant d'être transmises à un futur système de
Machine Learning permettant de détecter des situations anormales.

In [2]:
# importation des bibliotheque
import pandas as pd
import pandas as pd

# Partie 1 – Series

## 1) Créer une Series contenant 4 températures

In [3]:
# une series contenant 4 temperatures
temperatures = pd.Series([22.5, 24.1, 19.8, 26.3])
temperatures

0    22.5
1    24.1
2    19.8
3    26.3
dtype: float64

## 2) Afficher son index

In [4]:
temperatures.index

RangeIndex(start=0, stop=4, step=1)

## 3) Afficher la 1ère valeur

In [5]:
temperatures.iloc[0]

np.float64(22.5)

## 4) Afficher la dernière valeur

In [6]:
temperatures.iloc[-1]

np.float64(26.3)

## 5) Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de mesure 12h, 13h, 14h et 15h

In [7]:
# Méthode 1 : index passé lors de la création
temp_heures_1 = pd.Series([22.5, 24.1, 19.8, 26.3], index=["12h", "13h", "14h", "15h"])
temp_heures_1

12h    22.5
13h    24.1
14h    19.8
15h    26.3
dtype: float64

In [8]:
# Méthode 2 : création puis affectation de l'attribut .index
temp_heures_2 = pd.Series([22.5, 24.1, 19.8, 26.3])
temp_heures_2.index = ["12h", "13h", "14h", "15h"]
temp_heures_2

12h    22.5
13h    24.1
14h    19.8
15h    26.3
dtype: float64

## 6) Afficher la 1ère et la dernière valeur

In [13]:
print("Premier valeur",temp_heures_1.iloc[0])
print("Derniere valeur",temp_heures_1.iloc[-1])

Premier valeur 22.5
Derniere valeur 26.3

# Partie 2 – DataFrame

## 1) Créer et afficher le dataframe df_test à partir du dictionnaire suivant

In [21]:
data = {
"capteur": ["C001", "C002", "C003"],
"temperature": [24.5, 25.1, 26.3],
"humidite": [65, 67, 70]
}

df_test = pd.DataFrame(data)

df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

## 2) Importer le dataset mesures_capteurs.csv dans le dataframe df

In [20]:
df = pd.read_csv("/home/adama/atelier_pandas_iot/data/mesures_capteurs.csv")
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

## 3) Afficher les dimensions de df

In [22]:
df.shape

(605, 9)